server.error.include-message=always
server.error.include-binding-errors=always
spring.application.name=backend
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.profiles.default=dev
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs